config/routes.rb
Rails.application.routes.draw do

  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]

  root 'visitors#new'

end

app/models/contact.rb
require 'google_drive_v0'

class Contact

  include ActiveModel::Model

  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string

  validates :name, :email, :content, presence: true
  validates :email, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }
  validates :content, length: { maximum: 500 }

  def update_spreadsheet

    connection = GoogleDriveV0.login(Rails.application.secrets.email_provider_username, Rails.application.secrets.email_provider_password)
    ss = connection.spreadsheet_by_title("Learn-Rails-Example")
    if ss.nil?
      ss = connection.create_spreadsheet("Learn-Rails-Example")
    end

    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
    
  end


end

app/models/owner.rb
class Owner

  def name
    name = "Foobar Kadigan"
  end

  def birthdate
    birthdate = Date.new(1990,12,22)
  end

  def countdown
    today = Date.today
    birthday = Date.new(today.year, birthdate.month, birthdate.day)
    if today > birthday
      countdown = (birthday.next_year - birthday).to_i
    else
      countdown = (birthday - today).to_i
    end
  end
  
end

app/models/visitor.rb
class Visitor

  include ActiveModel::Model
  attr_accessor :email

  validates :email, presence: true, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }

  def subscribe
    mailchimp = Gibbon::API.new(Rails.application.secrets.mailchimp_api_key)
    result = mailchimp.lists.subscribe({

      id: Rails.application.secrets.mailchimp_list_id,
      email: {email: self.email},
      double_optin: false, 
      update_existing: true,
      send_welcome: true

    })

    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result

  end






end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end


  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver

      flash[:notice] = "Message sent from #{@contact.name}"
      redirect_to root_path

    else
      render :new
    end

  end


  private
  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end


end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @owner = Owner.new
    @visitor = Visitor.new

  end


  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed Up #{@visitor.email}"
      redirect_to root_path

    else
      render :new

    end


  end


  private
  def secure_params
    params.require(:visitor).permit(:email)

  end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>
Contact
<% end %>


<h1>Contact Me</h1>
<div class="form">


  <%= simple_form_for @contact do |form| %>
    <%= form.error_notification %>
    <%= form.input :name, autofocus: true %>
    <%= form.input :email  %>
    <%= form.input :content, as: :text  %>
    <%= form.button :submit, "Submit", class: "submit" %>

  <% end %>
  


</div>

app/views/contacts/process_form.html.erb
<h1>Contacts#process_form</h1>
<p>Find me in app/views/contacts/process_form.html.erb</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "About", page_path('about') %></li>
<li><%= link_to "Contact", new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :about do %>
    About
<% end %>

<h3>About</h3>
<p>Foobar Kadigan</p>
<p>????????</p>
<p>???????</p>

app/views/pages/home.html.erb
<% content_for :title do %>
  About
<% end %>
<h3>About Foobar Kadigan</h3>
<p>He was a special person</p>
<p>??????</p>
<p>??????</p>

app/views/visitors/new.html.erb
<h3>Home</h3>
<p>Welcome to the home of <%= @owner.name %></p>
<p>I was born in <%= @owner.birthdate %></p>
<p>Only <%= @owner.countdown %> days until my birthday</p>

<section>
  <img src="http://lorempixel.com/1170/600/cats/1">
</section>

<section>
<h2>Stay In touch!</h2>

<div class="form">
  <%= simple_form_for @visitor do |f| %>
    <%= f.error_notification %>


    <%= f.input :email, label: false, placeholder: "Your Email Address..."  %>
    <br/>

    <%= f.submit "Sign up for the newsletter"  %>





  <% end %>

</div>




  


</div>



</section>